// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Elevate.Recruit
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class Application : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"Application\",\"namespace\":\"Elevate.Recruit\",\"fields\":[{\"n" +
				"ame\":\"id\",\"type\":\"string\"},{\"name\":\"score\",\"type\":\"string\"},{\"name\":\"candidate_i" +
				"d\",\"type\":\"string\"},{\"name\":\"vacancy_is\",\"type\":\"string\"}]}");
		private string _id;
		private string _score;
		private string _candidate_id;
		private string _vacancy_is;
		public virtual Schema Schema
		{
			get
			{
				return Application._SCHEMA;
			}
		}
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		public string score
		{
			get
			{
				return this._score;
			}
			set
			{
				this._score = value;
			}
		}
		public string candidate_id
		{
			get
			{
				return this._candidate_id;
			}
			set
			{
				this._candidate_id = value;
			}
		}
		public string vacancy_is
		{
			get
			{
				return this._vacancy_is;
			}
			set
			{
				this._vacancy_is = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.id;
			case 1: return this.score;
			case 2: return this.candidate_id;
			case 3: return this.vacancy_is;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.id = (System.String)fieldValue; break;
			case 1: this.score = (System.String)fieldValue; break;
			case 2: this.candidate_id = (System.String)fieldValue; break;
			case 3: this.vacancy_is = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
